### ISSUE TITLE
Perfomance on firefox

### ISSUE THREAD

**Issue by sk29110** [evoluteur/structured-filter#3] opened 2015-07-07 00:25 UTC
Hello I am using this plugin but seems like it gets really slow when adding/removing filters even in the demo page. Do you have any idea why it becomes slow on firefox?

**Comment by evoluteur** [comment] 2015-09-21 01:35
Thanks for letting me know. The issue is now fixed (in version 1.0.7).

**Closed by evoluteur** 2015-09-21 01:35 UTC
